Merge arm & end effector
Team-4795/2023-Charged-Up pull request #2
Opened 2023-02-05 20:56 UTC by SuperWinner50

2023-02-06 01:40 UTC, sjiyeng approved these changes
Code looks good, sometime in the near future you should move a bunch of stuff into the constants file. It makes it a lot easier to make changes when testing or need to make quick fixes at comps

2023-02-06 13:35 UTC, akiyeng2 requested changes
Overall looks great! There's some minor changes to be made but should be a pretty quick fix @natashalrp @SuperWinner50

2023-02-06 13:35 UTC, akiyeng2 commented on src/main/java/frc/robot/subsystems/LiftArm.java
> +    // leftArmMotor.setSoftLimit(CANSparkMax.SoftLimitDirection.kForward, 65);
Reenable these soft limits and test

2023-02-06 13:35 UTC, akiyeng2 commented on src/main/java/frc/robot/subsystems/LiftArm.java
> +    rightArmMotor.setInverted(false);
This can be removed now

2023-02-06 13:35 UTC, akiyeng2 commented on src/main/java/frc/robot/subsystems/endEffectorIntake.java
> +public class endEffectorIntake extends SubsystemBase {
Capitalize filename and class name

2023-02-06 13:35 UTC, akiyeng2 commented on src/main/java/frc/robot/subsystems/endEffectorIntake.java
> +    public void intake()
Refactor to just have one setSpeed method with a variable speed, and set appropriate changes in RobotContainer

2023-02-07 01:49 UTC, akiyeng2 approved these changes

2023-02-07 01:49 UTC, akiyeng2 commented
Arm and end effector look good, great work Aaron, Halil, Natasha!

2023-02-07 01:50 UTC, merged